server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        - id: security-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api/public/**
          filters:
            - StripPrefix=1

        # Route for /api/v1/characters/** to launcher-service
        - id: launcher-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/v1/characters/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/characters to launcher-service /v3/api-docs
        - id: api-docs-launcher-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/characters
          filters:
            - RewritePath=/api-docs/characters,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs