server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        - id: security-service-route
          uri: http://security-service:4005
          predicates:
            - Path=/api/public/**
          filters:
            - StripPrefix=1

        # Route for /api/v1/characters/** to launcher-service
        - id: launcher-service-route
          uri: http://launcher-service:4000
          predicates:
            - Path=/api/v1/characters/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/characters to launcher-service /v3/api-docs
        - id: api-docs-launcher-route
          uri: http://launcher-service:4000
          predicates:
            - Path=/api-docs/launcher
          filters:
            - RewritePath=/api-docs/launcher,/v3/api-docs

        - id: api-docs-security-route
          uri: http://security-service:4005
          predicates:
            - Path=/api-docs/security
          filters:
            - RewritePath=/api-docs/security,/v3/api-docs